### ISSUE TITLE
float

### ISSUE THREAD

**Issue by starkegunnar** [Jaxc/Hjalmar#2]
"The STM32F4 only supports 32 bit floating point in hardware, so these functions must be done in software and will take many cycles to execute. To ensure that all calculations are done in 32 bit you should define all your floating point numbers (including constants) as type float."

https://github.com/Jaxc/Hjalmar/blob/d846d508b1ccd7ff416696542022fa13970c10b5/Src/audio_gen.c#L137

**Comment by Jaxc** [comment]
Fixed
